### ISSUE TITLE
APK?

### ISSUE THREAD

**Issue by webknjaz** [relisher/eMerge#3]
Hey!
The app looks cool (from the description).
Is there any apk available for downloading?

**Comment by relisher** [comment]
Hey-o! Unfortunately we never released an APK. If you would like to make one yourself, it should be possible using this code. There should be instructions on how to do that here:
http://android.stackexchange.com/questions/60358/how-can-i-compile-an-android-apk-from-source

## 

Антон

**Comment by webknjaz** [comment]
Thanks :)
